name: Reusable workflow
on:
  workflow_call:
    inputs:
      artifact_name:
        description: "Name of the artifact to download"
        type: string
        default: dist
        required: false
    outputs:
      result:
        description: "The downloaded artifact"
        value: "${{ jobs.deploy.outputs.outcome}}"

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      outcome: ${{ steps.outcome_id.outputs.outcome}}
    steps:
      - name: Dowloading artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{inputs.artifact_name}}
      - name: Listing th download artifacts
        run: ls
      - name: Setting output for the job
        id: outcome_id
        run: echo "outcome=myOutcome" >> "$GITHUB_OUTPUT"
      - name: Deploying to productio
        run: echo "Running reusable workflow"
